const fs = require('fs');

// We will build a complete dataset containing 132 chapters and authentic duas for ALL 132 chapters.

const chapters = [
  { id: 'ch_1', chapter_number: 1, title_bn: 'ঘুম থেকে জাগার যিকর', title_ar: 'أذكار الاستيقاظ من النوم', category_slug: 'waking_up', iconName: 'Moon' },
  { id: 'ch_2', chapter_number: 2, title_bn: 'পোশাক পরিধানের দো‘আ', title_ar: 'دعاء لبس الثوب', category_slug: 'wearing_garment', iconName: 'Shirt' },
  { id: 'ch_3', chapter_number: 3, title_bn: 'নতুন পোশাক পরিধানের দো‘আ', title_ar: 'دعاء لبس الثوب الجديد', category_slug: 'new_garment', iconName: 'Shirt' },
  { id: 'ch_4', chapter_number: 4, title_bn: 'কাউকে নতুন পোশাক পরতে দেখলে দো‘আ', title_ar: 'الدعاء لمن لبس ثوباً جديداً', category_slug: 'someone_new_garment', iconName: 'Shirt' },
  { id: 'ch_5', chapter_number: 5, title_bn: 'পোশাক খোলার সময় দো‘আ', title_ar: 'ما يقول إذا وضع ثوبه', category_slug: 'undressing', iconName: 'Shirt' },
  { id: 'ch_6', chapter_number: 6, title_bn: 'টয়লেট বা শৌচাগারে প্রবেশের দো‘আ', title_ar: 'دعاء دخول الخلاء', category_slug: 'entering_toilet', iconName: 'Droplets' },
  { id: 'ch_7', chapter_number: 7, title_bn: 'টয়লেট থেকে বের হওয়ার দো‘আ', title_ar: 'دعاء الخروج من الخلاء', category_slug: 'exiting_toilet', iconName: 'Droplets' },
  { id: 'ch_8', chapter_number: 8, title_bn: 'অযুর শুরুর দো‘আ', title_ar: 'الذكر قبل الوضوء', category_slug: 'before_wudu', iconName: 'Droplets' },
  { id: 'ch_9', chapter_number: 9, title_bn: 'অযুর শেষের দো‘আ', title_ar: 'الذكر بعد الفراغ من الوضوء', category_slug: 'after_wudu', iconName: 'Droplets' },
  { id: 'ch_10', chapter_number: 10, title_bn: 'ঘর থেকে বের হওয়ার দো‘আ', title_ar: 'الذكر عند الخروج من المنزل', category_slug: 'leaving_home', iconName: 'Landmark' },
  { id: 'ch_11', chapter_number: 11, title_bn: 'ঘরে প্রবেশের দো‘আ', title_ar: 'الذكر عند دخول المنزل', category_slug: 'entering_home', iconName: 'Landmark' },
  { id: 'ch_12', chapter_number: 12, title_bn: 'মসজিদে গমনের দো‘আ', title_ar: 'دعاء الذهاب إلى المسجد', category_slug: 'going_to_mosque', iconName: 'Landmark' },
  { id: 'ch_13', chapter_number: 13, title_bn: 'মসজিদে প্রবেশের দো‘আ', title_ar: 'دعاء دخول المسجد', category_slug: 'entering_mosque', iconName: 'Landmark' },
  { id: 'ch_14', chapter_number: 14, title_bn: 'মসজিদ থেকে বের হওয়ার দো‘আ', title_ar: 'دعاء الخروج من المسجد', category_slug: 'exiting_mosque', iconName: 'Landmark' },
  { id: 'ch_15', chapter_number: 15, title_bn: 'আযানের যিকর', title_ar: 'أذكار الأذان', category_slug: 'adhan_dhikr', iconName: 'Clock' },
  { id: 'ch_16', chapter_number: 16, title_bn: 'তাকবীরে তাহরীমার পরের দো‘আ (ইফতেতাহ)', title_ar: 'دعاء الاستفتاح', category_slug: 'opening_prayer_dua', iconName: 'Clock' },
  { id: 'ch_17', chapter_number: 17, title_bn: 'রুকূর যিকর ও দো‘আ', title_ar: 'دعاء الركوع', category_slug: 'ruku_dhikr', iconName: 'Clock' },
  { id: 'ch_18', chapter_number: 18, title_bn: 'রুকূ থেকে ওঠার পরের যিকর', title_ar: 'دعاء الرفع من الركوع', category_slug: 'rising_from_ruku', iconName: 'Clock' },
  { id: 'ch_19', chapter_number: 19, title_bn: 'সিজদার যিকর ও দো‘আ', title_ar: 'دعاء السجود', category_slug: 'sujud_dhikr', iconName: 'Clock' },
  { id: 'ch_20', chapter_number: 20, title_bn: 'দুই সিজদার মধ্যবর্তী বৈঠকের দো‘আ', title_ar: 'دعاء الجلسة بين السجدتين', category_slug: 'between_sujuds', iconName: 'Clock' },
  { id: 'ch_21', chapter_number: 21, title_bn: 'সিজদায়ে তিলাওয়াতের দো‘আ', title_ar: 'دعاء سجود التلاوة', category_slug: 'prostration_recitation', iconName: 'BookOpen' },
  { id: 'ch_22', chapter_number: 22, title_bn: 'তাশাহহুদ', title_ar: 'التشهد', category_slug: 'tashahhud', iconName: 'Clock' },
  { id: 'ch_23', chapter_number: 23, title_bn: 'তাশাহহুদের পর নবী (সা.)-এর ওপর দরূদ', title_ar: 'الصلاة على النبي بعد التشهد', category_slug: 'salawat_after_tashahhud', iconName: 'Sparkles' },
  { id: 'ch_24', chapter_number: 24, title_bn: 'সালাম ফেরানোর পূর্বে শেষ তাশাহহুদের পরের দো‘আ', title_ar: 'الدعاء بعد التشهد الأخير قبل السلام', category_slug: 'dua_before_taslim', iconName: 'Clock' },
  { id: 'ch_25', chapter_number: 25, title_bn: 'সালাতে সালাম ফেরানোর পরের যিকর', title_ar: 'الأذكار بعد السلام من الصلاة', category_slug: 'after_prayer_dhikr', iconName: 'Clock' },
  { id: 'ch_26', chapter_number: 26, title_bn: 'ইস্তিখারা সালাতের দো‘আ', title_ar: 'دعاء صلاة الاستخارة', category_slug: 'istikharah', iconName: 'Compass' },
  { id: 'ch_27', chapter_number: 27, title_bn: 'সকাল-সন্ধ্যার যিকর', title_ar: 'أذكار الصباح والمساء', category_slug: 'morning_evening_dhikr', iconName: 'Sun' },
  { id: 'ch_28', chapter_number: 28, title_bn: 'শোয়ার সময়ের যিকর', title_ar: 'أذكار النوم', category_slug: 'sleep_dhikr', iconName: 'Moon' },
  { id: 'ch_29', chapter_number: 29, title_bn: 'রাতে ঘুম ভাঙলে বা এপাশ-ওপাশ করার সময়ের দো‘আ', title_ar: 'الدعاء إذا تقلب ليلاً', category_slug: 'tossing_at_night', iconName: 'Moon' },
  { id: 'ch_30', chapter_number: 30, title_bn: 'ঘুমে ভয় পেলে বা একাকী বোধ করলে দো‘আ', title_ar: 'دعاء الفزع في النوم', category_slug: 'fearing_in_sleep', iconName: 'Moon' },
  { id: 'ch_31', chapter_number: 31, title_bn: 'স্বপ্নের ক্ষেত্রে করণীয় ও দো‘আ', title_ar: 'ما يفعل من رأى الرؤيا أو الحلم', category_slug: 'bad_dreams', iconName: 'Moon' },
  { id: 'ch_32', chapter_number: 32, title_bn: 'কুনূতে বিত্রের দো‘আ', title_ar: 'دعاء قنوت الوتر', category_slug: 'qunoot_witr', iconName: 'Clock' },
  { id: 'ch_33', chapter_number: 33, title_bn: 'বিত্রের সালাতে সালাম ফেরানোর পরের যিকর', title_ar: 'الذكر عقب السلام من الوتر', category_slug: 'after_witr', iconName: 'Clock' },
  { id: 'ch_34', chapter_number: 34, title_bn: 'দুশ্চিন্তা ও বেদনার দো‘আ', title_ar: 'دعاء الهم والحزن', category_slug: 'anxiety_sorrow', iconName: 'ShieldAlert' },
  { id: 'ch_35', chapter_number: 35, title_bn: 'বিপদে পড়া ও চরম কষ্টের সময়ের দো‘আ', title_ar: 'دعاء الكرب', category_slug: 'distress', iconName: 'ShieldAlert' },
  { id: 'ch_36', chapter_number: 36, title_bn: 'শত্রু ও পরাক্রমশালীদের সাক্ষাতে দো‘আ', title_ar: 'دعاء لقاء العدو وذي السلطان', category_slug: 'encountering_enemy', iconName: 'ShieldAlert' },
  { id: 'ch_37', chapter_number: 37, title_bn: 'শাসকের অত্যাচারের ভয়ে দো‘আ', title_ar: 'دعاء من خاف ظلم السلطان', category_slug: 'oppressive_ruler', iconName: 'ShieldAlert' },
  { id: 'ch_38', chapter_number: 38, title_bn: 'শত্রুর বিরুদ্ধে দো‘আ', title_ar: 'الدعاء على العدو', category_slug: 'against_enemy', iconName: 'ShieldAlert' },
  { id: 'ch_39', chapter_number: 39, title_bn: 'কোনো সম্প্রদায়কে ভয় পেলে দো‘আ', title_ar: 'ما يقول من خاف قوماً', category_slug: 'fearing_people', iconName: 'ShieldAlert' },
  { id: 'ch_40', chapter_number: 40, title_bn: 'ঈমানে সংশয় দেখা দিলে দো‘আ', title_ar: 'دعاء من أصابه وسوسة في الإيمان', category_slug: 'doubts_in_faith', iconName: 'Sparkles' },
  { id: 'ch_41', chapter_number: 41, title_bn: 'ঋণ মুক্তির দো‘আ', title_ar: 'دعاء قضاء الدين', category_slug: 'paying_debt', iconName: 'ShieldAlert' },
  { id: 'ch_42', chapter_number: 42, title_bn: 'সালাত ও তিলাওয়াতে ওয়াসওয়াসা দূর করার দো‘আ', title_ar: 'دعاء الوسوسة في الصلاة والقراءة', category_slug: 'whispers_in_prayer', iconName: 'Clock' },
  { id: 'ch_43', chapter_number: 43, title_bn: 'কঠিন কাজে পতিত হলে দো‘আ', title_ar: 'دعاء من استصعب عليه أمر', category_slug: 'difficult_matter', iconName: 'ShieldAlert' },
  { id: 'ch_44', chapter_number: 44, title_bn: 'পাপ কাজ সংঘটিত হলে করণীয় ও তাওবা', title_ar: 'ما يقول ويفر من أذنب ذنباً', category_slug: 'committing_sin', iconName: 'Sparkles' },
  { id: 'ch_45', chapter_number: 45, title_bn: 'শয়তান ও তার কুমন্ত্রণা দূর করার দো‘আ', title_ar: 'دعاء طرد الشيطان ووساوسه', category_slug: 'expelling_shaytan', iconName: 'ShieldAlert' },
  { id: 'ch_46', chapter_number: 46, title_bn: 'অপ্রীতিকর কিছু ঘটলে বা কাজে ব্যর্থ হলে দো‘আ', title_ar: 'الدعاء حينما يقع ما لا يرضاه', category_slug: 'unfavorable_event', iconName: 'ShieldAlert' },
  { id: 'ch_47', chapter_number: 47, title_bn: 'নবজাতকের অভিনন্দন ও তার উত্তর', title_ar: 'تهنئة المولود له وجوابه', category_slug: 'newborn_congratulation', iconName: 'Heart' },
  { id: 'ch_48', chapter_number: 48, title_bn: 'শিশুদের সুরক্ষায় আশ্রয় প্রার্থনা', title_ar: 'ما يعوذ به الأولاد', category_slug: 'protecting_children', iconName: 'Heart' },
  { id: 'ch_49', chapter_number: 49, title_bn: 'রোগীকে দেখতে গেলে পড়ার দো‘আ', title_ar: 'دعاء عيادة المريض', category_slug: 'visiting_sick', iconName: 'Activity' },
  { id: 'ch_50', chapter_number: 50, title_bn: 'রোগীর সেবা করার ফযীলত ও দো‘আ', title_ar: 'فضل عيادة المريض', category_slug: 'virtue_visiting_sick', iconName: 'Activity' },
  { id: 'ch_51', chapter_number: 51, title_bn: 'জীবনের আশা ছেড়ে দেওয়া রোগীর দো‘আ', title_ar: 'دعاء المريض الذي يئس من حياته', category_slug: 'hopeless_sick', iconName: 'Activity' },
  { id: 'ch_52', chapter_number: 52, title_bn: 'মুমূর্ষু ব্যক্তিকে তালকীন', title_ar: 'تلقين الاحتضار', category_slug: 'prompting_dying', iconName: 'Activity' },
  { id: 'ch_53', chapter_number: 53, title_bn: 'মুসীবতে পতিত হলে পড়ার দো‘আ', title_ar: 'دعاء من أصيب بمصيبة', category_slug: 'afflicted_calamity', iconName: 'ShieldAlert' },
  { id: 'ch_54', chapter_number: 54, title_bn: 'মাইয়্যিতের চোখ বন্ধ করার সময় দো‘আ', title_ar: 'الدعاء عند إغماض الميت', category_slug: 'closing_deceased_eyes', iconName: 'Activity' },
  { id: 'ch_55', chapter_number: 55, title_bn: 'জানাযার সালাতে মাইয়্যিতের জন্য দো‘আ', title_ar: 'الدعاء للميت في الصلاة عليه', category_slug: 'janazah_prayer_dua', iconName: 'Activity' },
  { id: 'ch_56', chapter_number: 56, title_bn: 'নাবালেগ শিশুর জানাযায় পড়ার দো‘আ', title_ar: 'الدعاء للفرط في الصلاة عليه', category_slug: 'janazah_child', iconName: 'Heart' },
  { id: 'ch_57', chapter_number: 57, title_bn: 'শোকাহত পরিবারকে সমবেদনা জ্ঞাপনের দো‘আ', title_ar: 'دعاء التعزية', category_slug: 'condolence', iconName: 'Heart' },
  { id: 'ch_58', chapter_number: 58, title_bn: 'মাইয়্যিতকে কবরে রাখার সময় দো‘আ', title_ar: 'الدعاء عند إدخال الميت القبر', category_slug: 'placing_in_grave', iconName: 'Activity' },
  { id: 'ch_59', chapter_number: 59, title_bn: 'দাফনের পর দো‘আ', title_ar: 'الدعاء بعد دفن الميت', category_slug: 'after_burial', iconName: 'Activity' },
  { id: 'ch_60', chapter_number: 60, title_bn: 'কবর যিয়ারতের দো‘আ', title_ar: 'دعاء زيارة القبور', category_slug: 'visiting_graves', iconName: 'Landmark' },
  { id: 'ch_61', chapter_number: 61, title_bn: 'তীব্র বাতাস বা ঝড়-তুফানের সময়ের দো‘আ', title_ar: 'دعاء الريح', category_slug: 'wind_storm', iconName: 'ShieldAlert' },
  { id: 'ch_62', chapter_number: 62, title_bn: 'মেঘের গর্জন শুনলে দো‘আ', title_ar: 'دعاء الرعد', category_slug: 'thunder', iconName: 'ShieldAlert' },
  { id: 'ch_63', chapter_number: 63, title_bn: 'বৃষ্টি চাওয়ার দো‘আ (ইস্তিসকা)', title_ar: 'من أدعية الاستسقاء', category_slug: 'rain_prayer', iconName: 'Droplets' },
  { id: 'ch_64', chapter_number: 64, title_bn: 'বৃষ্টি দেখার সময় দো‘আ', title_ar: 'الدعاء إذا رأى المطر', category_slug: 'seeing_rain', iconName: 'Droplets' },
  { id: 'ch_65', chapter_number: 65, title_bn: 'বৃষ্টির পর যিকর', title_ar: 'الذكر بعد نزول المطر', category_slug: 'after_rain', iconName: 'Droplets' },
  { id: 'ch_66', chapter_number: 66, title_bn: 'অতিবৃষ্টি বন্ধের দো‘আ', title_ar: 'من أدعية الاستصحاء', category_slug: 'stopping_rain', iconName: 'Droplets' },
  { id: 'ch_67', chapter_number: 67, title_bn: 'নতুন চাঁদ দেখার দো‘আ', title_ar: 'دعاء رؤية الهلال', category_slug: 'new_moon', iconName: 'Moon' },
  { id: 'ch_68', chapter_number: 68, title_bn: 'ইফতারের সময় দো‘আ', title_ar: 'دعاء الصائم عند إفطاره', category_slug: 'iftar_dua', iconName: 'Utensils' },
  { id: 'ch_69', chapter_number: 69, title_bn: 'খাওয়ার পূর্বে দো‘আ', title_ar: 'الدعاء قبل الطعام', category_slug: 'before_eating', iconName: 'Utensils' },
  { id: 'ch_70', chapter_number: 70, title_bn: 'খাওয়ার শেষের দো‘আ', title_ar: 'الدعاء عند الفراغ من الطعام', category_slug: 'after_eating', iconName: 'Utensils' },
  { id: 'ch_71', chapter_number: 71, title_bn: 'মেযবানের জন্য মেহমানের দো‘আ', title_ar: 'دعاء الضيف لرب الطعام', category_slug: 'guest_for_host', iconName: 'Utensils' },
  { id: 'ch_72', chapter_number: 72, title_bn: 'পানীয় বা খাবার প্রদানকারীর জন্য দো‘আ', title_ar: 'الدعاء لمن سقاه أو أراد ذلك', category_slug: 'for_one_who_offers_drink', iconName: 'Utensils' },
  { id: 'ch_73', chapter_number: 73, title_bn: 'যে পরিবারে ইফতার করা হয় তাদের জন্য দো‘আ', title_ar: 'الدعاء إذا أفطر عند أهل بيت', category_slug: 'host_iftaar', iconName: 'Utensils' },
  { id: 'ch_74', chapter_number: 74, title_bn: 'রোযাদারকে খাবার দিলে পড়ার দো‘আ', title_ar: 'دعاء الصائم إذا حضر الطعام ولم يفطر', category_slug: 'fasting_person_offered_food', iconName: 'Utensils' },
  { id: 'ch_75', chapter_number: 75, title_bn: 'কেউ গালি দিলে রোযাদারের বক্তব্য', title_ar: 'ما يقول الصائم إذا سابه أحد', category_slug: 'fasting_when_insulted', iconName: 'Utensils' },
  { id: 'ch_76', chapter_number: 76, title_bn: 'ফলের প্রথমাংশ দেখলে দো‘আ', title_ar: 'الدعاء عند رؤية ثمرة القوم', category_slug: 'first_fruit', iconName: 'Flower2' },
  { id: 'ch_77', chapter_number: 77, title_bn: 'হাঁচিদাতার দো‘আ ও তার উত্তর', title_ar: 'دعاء العاطس وجوابه', category_slug: 'sneezing', iconName: 'Activity' },
  { id: 'ch_78', chapter_number: 78, title_bn: 'কাফির হাঁচি দিয়ে আলহামদুলিল্লাহ বললে দো‘আ', title_ar: 'ما يقال للكافر إذا عطس فحمد الله', category_slug: 'disbeliever_sneezing', iconName: 'Activity' },
  { id: 'ch_79', chapter_number: 79, title_bn: 'বিবাহিত দম্পতির জন্য দো‘আ', title_ar: 'الدعاء للمتزوج', category_slug: 'congratulating_newlyweds', iconName: 'Heart' },
  { id: 'ch_80', chapter_number: 80, title_bn: 'বিবাহ ও বাহন ক্রয়ের পর দো‘আ', title_ar: 'دعاء المتزوج وشراء الدابة', category_slug: 'groom_and_buying_beast', iconName: 'Heart' },
  { id: 'ch_81', chapter_number: 81, title_bn: 'সহবাসের পূর্বের দো‘আ', title_ar: 'الدعاء قبل إتيان الزوجة', category_slug: 'before_intercourse', iconName: 'Heart' },
  { id: 'ch_82', chapter_number: 82, title_bn: 'রাগ দমনের দো‘আ', title_ar: 'دعاء الغضب', category_slug: 'suppressing_anger', iconName: 'ShieldAlert' },
  { id: 'ch_83', chapter_number: 83, title_bn: 'বিপদগ্রস্ত বা ব্যাধিগ্রস্ত লোক দেখলে দো‘আ', title_ar: 'دعاء من رأى مبتلى', category_slug: 'seeing_afflicted_person', iconName: 'Activity' },
  { id: 'ch_84', chapter_number: 84, title_bn: 'মজলিসের দো‘আ', title_ar: 'ما يقال في المجلس', category_slug: 'sitting_in_gathering', iconName: 'Landmark' },
  { id: 'ch_85', chapter_number: 85, title_bn: 'মজলিস ভঙ্গের কাফফারা', title_ar: 'دعاء كفارة المجلس', category_slug: 'expiation_gathering', iconName: 'Landmark' },
  { id: 'ch_86', chapter_number: 86, title_bn: 'কেউ \'আল্লাহ আপনাকে ক্ষমা করুন\' বললে উত্তর', title_ar: 'الدعاء لمن قال غفر الله لك', category_slug: 'reply_forgiveness', iconName: 'Sparkles' },
  { id: 'ch_87', chapter_number: 87, title_bn: 'কেউ আপনার কোনো উপকার করলে দো‘আ', title_ar: 'الدعاء لمن صنع إليك معروفاً', category_slug: 'for_one_who_does_good', iconName: 'Sparkles' },
  { id: 'ch_88', chapter_number: 88, title_bn: 'দাজ্জাল থেকে আত্মরক্ষার আমল', title_ar: 'ما يعصم الله به من الدجال', category_slug: 'protection_from_dajjal', iconName: 'ShieldAlert' },
  { id: 'ch_89', chapter_number: 89, title_bn: 'কেউ ভালোবাসার কথা প্রকাশ করলে উত্তর', title_ar: 'الدعاء لمن قال إني أحبك في الله', category_slug: 'expressed_love_for_allah', iconName: 'Heart' },
  { id: 'ch_90', chapter_number: 90, title_bn: 'কেউ ধন-সম্পদ পেশ করলে তার জন্য দো‘আ', title_ar: 'الدعاء لمن عرض عليك ماله', category_slug: 'offered_wealth', iconName: 'Sparkles' },
  { id: 'ch_91', chapter_number: 91, title_bn: 'ঋণ পরিশোধ করার সময় ঋণদাতার জন্য দো‘আ', title_ar: 'الدعاء لمن اقترضت منه عند القضاء', category_slug: 'repaying_creditor', iconName: 'ShieldAlert' },
  { id: 'ch_92', chapter_number: 92, title_bn: 'শিরকের ভয়ে পড়ার দো‘আ', title_ar: 'دعاء الخوف من الشرك', category_slug: 'fearing_shirk', iconName: 'ShieldAlert' },
  { id: 'ch_93', chapter_number: 93, title_bn: 'কেউ \'আল্লাহ আপনাকে বরকত দিন\' বললে উত্তর', title_ar: 'الدعاء لمن قال بارك الله فيك', category_slug: 'reply_barakallah', iconName: 'Sparkles' },
  { id: 'ch_94', chapter_number: 94, title_bn: 'কুলক্ষণ বা অলক্ষণ বর্জনের দো‘আ', title_ar: 'دعاء كراهية الطيرة', category_slug: 'disliking_omens', iconName: 'ShieldAlert' },
  { id: 'ch_95', chapter_number: 95, title_bn: 'বাহনে আরোহণের দো‘আ', title_ar: 'دعاء ركوب الدابة', category_slug: 'mounting_mount', iconName: 'Compass' },
  { id: 'ch_96', chapter_number: 96, title_bn: 'সফরের দো‘আ', title_ar: 'دعاء السفر', category_slug: 'travel_dua', iconName: 'Compass' },
  { id: 'ch_97', chapter_number: 97, title_bn: 'গ্রাম বা শহরে প্রবেশের দো‘আ', title_ar: 'دعاء دخول القرية أو البلدة', category_slug: 'entering_town', iconName: 'Compass' },
  { id: 'ch_98', chapter_number: 98, title_bn: 'বাজারে প্রবেশের দো‘আ', title_ar: 'دعاء دخول السوق', category_slug: 'entering_market', iconName: 'Compass' },
  { id: 'ch_99', chapter_number: 99, title_bn: 'সফরকালে বাহন হোঁচট খেলে দো‘আ', title_ar: 'الدعاء إذا تعس المركوب', category_slug: 'stumbling_mount', iconName: 'Compass' },
  { id: 'ch_100', chapter_number: 100, title_bn: 'মুকীদের জন্য মুসাফিরের দো‘আ', title_ar: 'دعاء المسافر للمقيم', category_slug: 'traveler_for_resident', iconName: 'Compass' },
  { id: 'ch_101', chapter_number: 101, title_bn: 'মুসাফিরের জন্য মুকীদের দো‘আ', title_ar: 'دعاء المقيم للمسافر', category_slug: 'resident_for_traveler', iconName: 'Compass' },
  { id: 'ch_102', chapter_number: 102, title_bn: 'সফরকালে পাহাড়ে উঠা ও নামার সময়ের তাকবীর ও তাসবীহ', title_ar: 'التكبير والتسبيح في سير السفر', category_slug: 'ascending_descending_travel', iconName: 'Compass' },
  { id: 'ch_103', chapter_number: 103, title_bn: 'মুসাফির শেষ রাতে যে দো‘আ পড়বে', title_ar: 'دعاء المسافر إذا أسيحر', category_slug: 'traveler_at_dawn', iconName: 'Compass' },
  { id: 'ch_104', chapter_number: 104, title_bn: 'কোথাও অবস্থান নিলে পড়ার দো‘আ', title_ar: 'الدعاء إذا نزل منزلاً في سفر أو غيره', category_slug: 'stopping_at_dwelling', iconName: 'Compass' },
  { id: 'ch_105', chapter_number: 105, title_bn: 'সফর থেকে প্রত্যাবর্তনের যিকর', title_ar: 'ذكر الرجوع من السفر', category_slug: 'returning_from_travel', iconName: 'Compass' },
  { id: 'ch_106', chapter_number: 106, title_bn: 'আনন্দের কোনো খবর পেলে বা ভালো ঘটনা দেখলে দো‘আ', title_ar: 'ما يقول من أتاه أمر يسره أو يكرهه', category_slug: 'pleasing_event', iconName: 'Sparkles' },
  { id: 'ch_107', chapter_number: 107, title_bn: 'অপ্রিয় ঘটনা দেখলে বা শুনলে পড়ার দো‘আ', title_ar: 'ما يقول من أتاه أمر يكرهه', category_slug: 'displeasing_event', iconName: 'ShieldAlert' },
  { id: 'ch_108', chapter_number: 108, title_bn: 'দরূদ শরীফ পাঠের ফযীলত ও দো‘আ', title_ar: 'فضل الصلاة على النبي', category_slug: 'virtue_salawat', iconName: 'Sparkles' },
  { id: 'ch_109', chapter_number: 109, title_bn: 'সালাম প্রসারের ফযীলত ও বিধান', title_ar: 'إفشاء السلام', category_slug: 'spreading_salam', iconName: 'Heart' },
  { id: 'ch_110', chapter_number: 110, title_bn: 'কাফির সালাম দিলে তার উত্তর', title_ar: 'كيف يرد على الكافر إذا سلم', category_slug: 'reply_salam_non_muslim', iconName: 'Heart' },
  { id: 'ch_111', chapter_number: 111, title_bn: 'মোরগের ডাক ও গাধার ডাক শুনলে দো‘আ', title_ar: 'الدعاء عند سماع صياح الديك ونهيق الحمار', category_slug: 'hearing_rooster_donkey', iconName: 'Activity' },
  { id: 'ch_112', chapter_number: 112, title_bn: 'রাতে কুকুরের ঘেউ ঘেউ শুনলে দো‘আ', title_ar: 'الدعاء عند سماع نباح الكلاب بالليل', category_slug: 'hearing_barking_dogs', iconName: 'Activity' },
  { id: 'ch_113', chapter_number: 113, title_bn: 'যাকে আপনি গালি দিয়েছেন তার জন্য দো‘আ', title_ar: 'الدعاء لمن سببته', category_slug: 'for_one_you_insulted', iconName: 'Heart' },
  { id: 'ch_114', chapter_number: 114, title_bn: 'মুসলিম অপর মুসলিমের প্রশংসা করলে যা বলবে', title_ar: 'ما يقول المسلم إذا زكى المسلم', category_slug: 'praising_fellow_muslim', iconName: 'Heart' },
  { id: 'ch_115', chapter_number: 115, title_bn: 'প্রশংসিত ব্যক্তি যা বলবে', title_ar: 'ما يقول المسلم إذا زُكِّيَ', category_slug: 'when_praised', iconName: 'Heart' },
  { id: 'ch_116', chapter_number: 116, title_bn: 'হজ্জ ও উমরার তালবিয়াহ', title_ar: 'كيف يلبي المحرم في الحج أو العمرة', category_slug: 'talbiya_hajj_umrah', iconName: 'Landmark' },
  { id: 'ch_117', chapter_number: 117, title_bn: 'হাজরে আসওয়াদ স্পর্শ ও তাওয়াফের তাকবীর', title_ar: 'التكبير عند أتيان الحجر الأسود', category_slug: 'at_black_stone', iconName: 'Landmark' },
  { id: 'ch_118', chapter_number: 118, title_bn: 'রুকনে ইয়ামানী ও হাজরে আসওয়াদের মাঝখানের দো‘আ', title_ar: 'الدعاء بين الركن اليماني والحجر الأسود', category_slug: 'between_yemeni_corner_black_stone', iconName: 'Landmark' },
  { id: 'ch_119', chapter_number: 119, title_bn: 'সাফা ও মারওয়া পাহাড়ে ওঠার পর দো‘আ', title_ar: 'دعاء الوقوف على الصفا والمروة', category_slug: 'at_safa_marwah', iconName: 'Landmark' },
  { id: 'ch_120', chapter_number: 120, title_bn: 'আরাফাতের ময়দানের দো‘আ', title_ar: 'الدعاء يوم عرفة', category_slug: 'day_of_arafah', iconName: 'Landmark' },
  { id: 'ch_121', chapter_number: 121, title_bn: 'মাশ\'আরে হারামে (মুযদালিফায়) যিকর', title_ar: 'الذكر عند المشعر الحرام', category_slug: 'at_mashar_al_haram', iconName: 'Landmark' },
  { id: 'ch_122', chapter_number: 122, title_bn: 'জামরায় কঙ্কর নিক্ষেপকালে তাকবীর', title_ar: 'التكبير عند رمي الجمار مع كل حصاة', category_slug: 'pelt_jamarat', iconName: 'Landmark' },
  { id: 'ch_123', chapter_number: 123, title_bn: 'বিস্ময় ও আনন্দের মুহূর্তে তাকবীর ও তাসবীহ', title_ar: 'ما يقول عند التعجب والأمر السار', category_slug: 'astonishment_joy', iconName: 'Sparkles' },
  { id: 'ch_124', chapter_number: 124, title_bn: 'কোনো সুসংবাদ পেয়ে আনন্দিত হলে করণীয়', title_ar: 'ما يفعل من أتاه أمر يسره', category_slug: 'good_news', iconName: 'Sparkles' },
  { id: 'ch_125', chapter_number: 125, title_bn: 'শরীরে কোনো ব্যথা অনুভব করলে দো‘আ', title_ar: 'ما يقول من أحس بوجع في جسده', category_slug: 'feeling_pain_in_body', iconName: 'Activity' },
  { id: 'ch_126', chapter_number: 126, title_bn: 'কুষ্টি বা নজর লাগার ভয়ে দো‘আ', title_ar: 'دعاء من خاف أن يصيب شيئاً بعينه', category_slug: 'fearing_evil_eye', iconName: 'Activity' },
  { id: 'ch_127', chapter_number: 127, title_bn: 'ভীত-সন্ত্রস্ত অবস্থায় যা বলতে হয়', title_ar: 'ما يقال عند الفزع', category_slug: 'frightened', iconName: 'ShieldAlert' },
  { id: 'ch_128', chapter_number: 128, title_bn: 'যবেহ বা কুরবানী করার সময় দো‘আ', title_ar: 'ما يقول عند الذبح أو النحر', category_slug: 'slaughtering_animal', iconName: 'Utensils' },
  { id: 'ch_129', chapter_number: 129, title_bn: 'শয়তানের চক্রান্ত ও ষড়যন্ত্র প্রতিহত করার দো‘আ', title_ar: 'ما يقول لرد كيد كفار الشياطين', category_slug: 'repelling_shaytan_plots', iconName: 'ShieldAlert' },
  { id: 'ch_130', chapter_number: 130, title_bn: 'তাওবা ও ইস্তিগফার (ক্ষমা প্রার্থনা)', title_ar: 'الاستغفار والتوبة', category_slug: 'tawbah_istighfar', iconName: 'Sparkles' },
  { id: 'ch_131', chapter_number: 131, title_bn: 'তাসবীহ, তাহমীদ, তাহলীল ও তাকবীরের ফযীলত', title_ar: 'فضل التسبيح والتحميد والتهليل والتكبير', category_slug: 'virtues_of_tasbih', iconName: 'Sparkles' },
  { id: 'ch_132', chapter_number: 132, title_bn: 'রাসূলুল্লাহ (সা.) যেভাবে তাসবীহ গণনা করতেন', title_ar: 'كيف كان النبي يسبح', category_slug: 'how_prophet_counted_tasbih', iconName: 'Clock' }
];

console.log('Chapters count:', chapters.length);
